### PR TITLE
Increase BUSY_CHECK_COUNT

### PR DESCRIPTION
**Pull request by timbz**
Needed to dd 3GB to mmc on a i.MX6

### CODE REVIEW

**Review by otavio — COMMENTED** [review]
Please elaborate more on the commit log. What error it fixes?

**Comment by timbz** [comment]
It avoids running into https://github.com/Freescale/utp_com/blob/master/utp_com.c#L298. Updated the commit message

**Review by otavio — APPROVED** [review]

**Comment by thochstein** [comment]
@otavio, I'm not familiar with this code.

**Comment by otavio** [comment]
@thochstein who can review this?

**Comment by thochstein** [comment]
Someone at Boundary Devices? @gibsson?

**Comment by gibsson** [comment]
I haven't used that tool in years so I'm not sure how much help I can give.
That being said, I see little to no harm to increase such a timeout count as it would indeed depend on many parameters. Ideally it could be something to overwrite as a parameter to avoid having to update it again in the future.

**Pull request merged**
